### ISSUE TITLE
JSONDecodeError while browsing the vendor

### ISSUE THREAD

**Issue by tbhaxor** [cve-search/PyCVESearch#12]
**Code**
```py
from pycvesearch import CVESearch
cve = CVESearch()
cve.search('microsoft/office')
```

**Complete Error**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pycvesearch/core.py", line 40, in search
    return data.json()
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by likema** [comment]
I encountered the same issue.

**Comment by tbhaxor** [comment]
@Rafiot  any updates?

**Comment by Rafiot** [comment]
Yes, the API endpoint you are using has been removed from the public instance due to massive abusive behavior. 
You can install a local version of CVE Search.

**Comment by likema** [comment]
@Rafiot Do you mean https://github.com/cve-search/cve-search ?

**Comment by Rafiot** [comment]
yes

**Comment by likema** [comment]
@Rafiot Can **PyCVESearch**  still be used for it?

**Comment by tbhaxor** [comment]
Ohk so how do i integrate it with python?

**Comment by Rafiot** [comment]
> @Rafiot Can **PyCVESearch** still be used for it?

Yes, just pass the URL of your instance to the library.

**Comment by Rafiot** [comment]
> Ohk so how do i integrate it with python?

What do you mean? You can pass the URL of your internal instance to the python library.

**Comment by tbhaxor** [comment]
AFAIK its a CLI

**Comment by Rafiot** [comment]
> AFAIK its a CLI

I'm super confused what you're talking about. There is no executable script in this library, and here is the documentation: https://github.com/cve-search/PyCVESearch#documentation

**Comment by tbhaxor** [comment]
Nevermind, I understood, I have to write my own package, -_-
