### ISSUE TITLE
search function is broken

### ISSUE THREAD

**Issue by Timo2208** [cve-search/PyCVESearch#13]
al other function's are working but search is crashing because a json decoding fault
  raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by Rafiot** [comment]
Are you running it against the public instance? If yes, please have a look at the readme: https://github.com/cve-search/PyCVESearch/blob/master/README.md

The API has been disabled.

You can setup CVE search yourself, and use PyCVESearch against it.

**Comment by Timo2208** [comment]
aah but i don't get CVE-search working properly

**Comment by Rafiot** [comment]
We may need more details to help you. Can you give us more details about it in an other issue in the cve-search repository.

**Comment by Timo2208** [comment]
i will do, thank you
